function jobInterface() {
  return {
    jobVacancyID: 0,
    fK_CompanyorDeptID: 0,
    lkpJobTitleID: 0,
    noOfVacancy: 0,
    description: '',
    announcementDate: new Date(),
    lateDatetoApply: new Date(),
    createD_BY: '',
    createD_DATE: new Date(),
    lasT_UPDATE_BY: '',
    lasT_UPDATE_DATE: new Date(),
    isActive: true,
    isDeleted: false,
    salary: 0,
    designation: '',
    department: 0,
    skillsRequired: '',
    city: 0,
    isRemoteJob: false,
    draft: true,
    jobType: '',
    male_Vacancy: 0,
    feMale_Vacancy: 0,
    experiance: 0,
    companyShortName: '',
    companyName: '',
    companyName_Ar: '',
    country: 0,
    address: '',
    phoneNumber: '',
    fax: '',
    lookUpValueCode: '',
    lookUpValue: '',
    lookUpValue_Ar: '',
  }
}

export default jobInterface
