import { Button, Form, Input } from 'antd'
import Head from 'next/head'
import { useMutation } from 'react-query'
import { useToasts } from 'react-toast-notifications'
import { forgotPassword } from '../stores/apis/auth_apis'
import styles from '../styles/auth.module.scss'

export default function ForgotPassword() {
  const { mutateAsync, isLoading, isSuccess } = useMutation(forgotPassword)
  const { addToast } = useToasts()

  const resetPassword = (values) => {
    mutateAsync(values, {
      onSuccess: async (response) => {
        addToast('password reset link has been sent to your email', {
          appearance: 'success',
          autoDismiss: true,
        })
      },
      onError: async (error) => {
        addToast('Email not found', {
          appearance: 'error',
          autoDismiss: true,
        })
      },
    })
  }

  return (
    <>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div style={{ width: '30%', margin: 'auto', marginTop: '100px' }}>
          <Form
            name="basic"
            layout="vertical"
            initialValues={{ remember: true }}
            onFinish={resetPassword}
            onFinishFailed={() => {}}
            autoComplete="off"
          >
            <Form.Item label="Email">
              <Form.Item
                label="Email"
                noStyle
                name="email"
                validateTrigger="onSubmit"
                rules={[{ required: true, type: 'email' }]}
              >
                <Input size="large" placeholder="bruce@wayne.com" />
              </Form.Item>
            </Form.Item>

            <Form.Item className={styles.frm_footer}>
              <Button
                type="primary"
                block
                loading={isLoading}
                htmlType="submit"
              >
                Submit
              </Button>
              {/* <span className={styles.back_step}><LeftOutlined /> Back</span> */}
            </Form.Item>
          </Form>
        </div>
      </main>
    </>
  )
}
