import Head from 'next/head'
import React from 'react'
import AuthLayout from '../components/Auth/authLayout'

const ProfileSuccess = () => {
  return (
    <div>
      <Head>
        <title>Profile Successfully Done</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AuthLayout>
        {/* <ShowSuccess title="Profile setup complete!" desc="Let's continue to setting up your Job Preferences." btnText="Set Job Preferences" /> */}
      </AuthLayout>
    </div>
  )
}

export default ProfileSuccess
