import Head from 'next/head'
import { useState } from 'react'
import AuthLayout from '../components/Auth/authLayout'
import SignupSplash from '../components/Auth/steps/signupSplash'

export default function Signup() {
  const [signMethod, setSignMethod] = useState()

  const checkSignupMethod = (method) => {
    setSignMethod(method)
  }

  return (
    <>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <AuthLayout step={1}>
          {!signMethod && <SignupSplash signupMethod={checkSignupMethod} />}
          {/* {signMethod === 'email' && } */}
        </AuthLayout>
      </main>
    </>
  )
}
