import Head from 'next/head'
import AuthLayout from '../components/Auth/authLayout'
import SignIn from '../components/Auth/signin'

export default function Signup() {
  return (
    <>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <AuthLayout page="signin">
          <SignIn />
        </AuthLayout>
      </main>
    </>
  )
}
