export const permissionsEnum = {
  postAJob: 1,
  editAJOb: 2,
  viewCandidates: 3,
  publishAJob: 4,
  approveCandidate: 5,
  shortlistCandidate: 6,
  rejectCandidate: 7,
  addCandidate: 8,
  deleteCategory: 9,
  userManagement: 10,
  roleManagement: 11,
  editCategory: 12,
  ViewReport: 13,
  Dashboard: 14,
  LookUps: 15,
  SystemsLogs: 16,
}
